// Package codegen — pdf_emitter.go
//
// PDFEmitter converts a validated AST into a professionally formatted PDF
// contract document using the go-pdf/fpdf library.
//
// REQ-3.1: No generative AI. Output is deterministic — identical inputs
// always produce identical PDFs (font metrics aside).
// REQ-3.3: Output is a .pdf file containing no residual DSL syntax.
package codegen

import (
	"fmt"
	"strings"

	"lexscript/pkg/ast"

	"github.com/go-pdf/fpdf"
)

// ---------------------------------------------------------------------------
// Layout constants
// ---------------------------------------------------------------------------

const (
	pdfPageWidth    = 210.0 // A4 mm
	pdfPageHeight   = 297.0 // A4 mm
	pdfMarginLeft   = 20.0
	pdfMarginRight  = 20.0
	pdfMarginTop    = 25.0
	pdfMarginBottom = 25.0
	pdfTextWidth    = pdfPageWidth - pdfMarginLeft - pdfMarginRight

	// Font sizes
	pdfFontTitle    = 18.0
	pdfFontH1       = 14.0
	pdfFontH2       = 12.0
	pdfFontBody     = 10.0
	pdfFontSmall    = 8.0
	pdfLineHeightH1 = 8.0
	pdfLineHeightH2 = 7.0
	pdfLineHeightB  = 6.0
)

// ---------------------------------------------------------------------------
// PDFEmitter
// ---------------------------------------------------------------------------

// PDFEmitter converts a validated AST into a PDF document.
type PDFEmitter struct{}

// NewPDFEmitter constructs a PDFEmitter.
func NewPDFEmitter() *PDFEmitter { return &PDFEmitter{} }

// EmitPDF walks the contract AST, builds ContractData, and renders to a PDF
// file at outPath.
func (pe *PDFEmitter) EmitPDF(c *ast.Contract, outPath string) error {
	// Re-use the same data model as the Markdown emitter.
	e := NewEmitter()
	data := e.buildData(c)
	return renderPDF(data, outPath)
}

// ---------------------------------------------------------------------------
// PDF rendering
// ---------------------------------------------------------------------------

func renderPDF(data ContractData, outPath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(pdfMarginLeft, pdfMarginTop, pdfMarginRight)
	pdf.SetAutoPageBreak(true, pdfMarginBottom)
	pdf.AddPage()

	// ── Header footer callback ──────────────────────────────────────────────
	pdf.SetHeaderFunc(func() {
		pdf.SetFont("Helvetica", "I", pdfFontSmall)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 5, titleCase(data.Title)+" - Confidential")
		pdf.Ln(3)
		pdf.SetTextColor(0, 0, 0)
	})
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", pdfFontSmall)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(pdfTextWidth/2, 5,
			"Generated by LexScript - deterministic output (REQ-3.1)", "", 0, "L", false, 0, "")
		pdf.CellFormat(pdfTextWidth/2, 5,
			fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "R", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	})

	// ── Title block ─────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", pdfFontTitle)
	pdf.MultiCell(pdfTextWidth, 10, titleCase(data.Title), "", "C", false)
	pdf.Ln(2)

	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Cell(pdfTextWidth/2, pdfLineHeightB, "Date: "+data.Date)
	pdf.Ln(pdfLineHeightB)
	pdf.Cell(pdfTextWidth/2, pdfLineHeightB, "Governing Law: Common Law")
	pdf.Ln(pdfLineHeightB + 3)

	hr(pdf)

	pdfBody(pdf,
		"This Agreement (\"Agreement\") is entered into as of "+data.Date+" by and between "+
			"the parties identified herein. The terms of this Agreement shall be governed by "+
			"and construed in accordance with applicable common law principles. The parties "+
			"intend this Agreement to be legally binding.")
	pdf.Ln(4)
	hr(pdf)

	// ── §1 Parties ──────────────────────────────────────────────────────────
	pdfH1(pdf, "1. Parties")
	pdfBody(pdf,
		"The following parties are bound by the terms of this Agreement:")
	pdf.Ln(2)
	for i, p := range data.Parties {
		pdfBullet(pdf, fmt.Sprintf("%d. %s", i+1, p))
	}
	pdf.Ln(2)
	pdfBody(pdf,
		"Each party represents and warrants that it has full legal capacity and authority "+
			"to enter into, execute, and perform its obligations under this Agreement.")
	pdf.Ln(4)
	hr(pdf)

	// ── §2 Definitions ──────────────────────────────────────────────────────
	pdfH1(pdf, "2. Definitions")
	pdfBody(pdf,
		"For the purposes of this Agreement, the following terms shall have the meanings "+
			"set forth below:")
	pdf.Ln(2)
	for _, a := range data.Amounts {
		pdfBullet(pdf, fmt.Sprintf(
			"**\"%s\"** means the amount of %s.", titleCase(a.Name), a.Display))
	}
	for _, tl := range data.TimeLimits {
		pdfBullet(pdf, fmt.Sprintf(
			"**\"%s\"** means a period of %s commencing from the date on which the "+
				"relevant obligation first becomes due.", titleCase(tl.Name), tl.Display))
	}
	pdf.Ln(2)
	pdfBody(pdf,
		"Any term not defined herein shall be given its ordinary meaning under applicable common law.")
	pdf.Ln(4)
	hr(pdf)

	// ── §3 Obligations & Performance ────────────────────────────────────────
	pdfH1(pdf, "3. Obligations and Performance")
	for _, s := range data.States {
		if s.IsTerminal {
			continue
		}
		pdf.Ln(3)
		pdfH2(pdf, "3. "+titleCase(s.Name))
		pdfLabel(pdf, "Phase: "+titleCase(s.Name))
		pdf.Ln(1)

		if len(s.Obligations) > 0 {
			pdfBody(pdf, "The following obligations apply during the "+
				titleCase(s.Name)+" phase:")
			pdf.Ln(1)
			for _, ob := range s.Obligations {
				pdfBullet(pdf, "**"+ob.Party+"** shall "+legalAction(ob.Action)+
					" the "+titleCase(ob.Object)+
					" as required under this Agreement. Failure to do so within the "+
					"prescribed time shall constitute a material breach of this clause.")
			}
		}

		if len(s.Transitions) > 0 {
			pdf.Ln(1)
			pdfLabel(pdf, "Applicable Transitions and Conditions:")
			pdf.Ln(1)
			for _, tr := range s.Transitions {
				pdfBullet(pdf, tr.LegalClause)
			}
		}
	}
	pdf.Ln(4)
	hr(pdf)

	// ── §4 Term and Termination ─────────────────────────────────────────────
	pdfH1(pdf, "4. Term and Termination")
	for _, s := range data.States {
		if !s.IsTerminal {
			continue
		}
		pdf.Ln(3)
		pdfH2(pdf, "4. "+titleCase(s.TermKind)+" - "+titleCase(s.Name))
		pdfBody(pdf, termClause(s.TermKind))
	}
	pdf.Ln(4)
	hr(pdf)

	// ── §5 General Provisions ───────────────────────────────────────────────
	pdfH1(pdf, "5. General Provisions")
	pdf.Ln(2)
	generalProvisions := []struct{ num, head, body string }{
		{"5.1", "Entire Agreement",
			"This Agreement constitutes the entire agreement between the parties with " +
				"respect to the subject matter hereof and supersedes all prior negotiations, " +
				"representations, warranties, and understandings, whether oral or written."},
		{"5.2", "Severability",
			"If any provision of this Agreement is held by a court of competent jurisdiction " +
				"to be invalid, illegal, or unenforceable, the remaining provisions shall " +
				"continue in full force and effect as if the invalid provision had never been included."},
		{"5.3", "Amendments",
			"No amendment, modification, or supplement to this Agreement shall be valid or " +
				"binding unless made in writing and duly executed by all parties."},
		{"5.4", "No Waiver",
			"The failure of any party to enforce any provision of this Agreement on any " +
				"occasion shall not be construed as a waiver of that party's right to enforce " +
				"that or any other provision on any other occasion."},
		{"5.5", "Force Majeure",
			"No party shall be liable for any failure or delay in performance caused by " +
				"circumstances beyond that party's reasonable control, provided that the affected " +
				"party gives prompt written notice to the other parties and uses reasonable " +
				"efforts to overcome the force majeure condition."},
		{"5.6", "Notices",
			"All notices required or permitted under this Agreement shall be in writing and " +
				"shall be deemed duly given when delivered personally, sent by confirmed " +
				"electronic transmission, or deposited in the mail with first-class postage prepaid."},
	}
	for _, p := range generalProvisions {
		pdf.SetFont("Helvetica", "B", pdfFontBody)
		pdf.Cell(0, pdfLineHeightB, p.num+" "+p.head+".")
		pdf.SetFont("Helvetica", "", pdfFontBody)
		pdf.Ln(pdfLineHeightB)
		pdf.MultiCell(pdfTextWidth, pdfLineHeightB, p.body, "", "J", false)
		pdf.Ln(2)
	}
	hr(pdf)

	// ── §6 Representations and Warranties ───────────────────────────────────
	pdfH1(pdf, "6. Representations and Warranties")
	pdfBody(pdf,
		"Each party hereby represents and warrants to the other parties as of the date "+
			"of this Agreement:")
	pdf.Ln(2)
	reps := []string{
		"It has full power and authority to enter into this Agreement.",
		"This Agreement has been duly authorised and constitutes a valid, binding, " +
			"and enforceable obligation of such party.",
		"The execution and performance of this Agreement does not violate any law, " +
			"regulation, order, or contract to which it is a party.",
	}
	for i, r := range reps {
		pdfBullet(pdf, fmt.Sprintf("%d. %s", i+1, r))
	}
	pdf.Ln(4)
	hr(pdf)

	// ── §7 Signatures ───────────────────────────────────────────────────────
	pdfH1(pdf, "7. Signatures")
	pdfItalic(pdf,
		"IN WITNESS WHEREOF, the parties have caused this Agreement to be executed "+
			"as of the date first written above.")
	pdf.Ln(6)
	for _, party := range data.Parties {
		pdf.SetFont("Helvetica", "B", pdfFontBody)
		pdf.Cell(0, pdfLineHeightB, party)
		pdf.Ln(pdfLineHeightB + 4)
		signatureLine(pdf, "Signature")
		signatureLine(pdf, "Printed Name")
		signatureLine(pdf, "Title / Role")
		signatureLine(pdf, "Date")
		pdf.Ln(6)
	}
	hr(pdf)

	// ── Footer notice ────────────────────────────────────────────────────────
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "I", pdfFontSmall)
	pdf.SetTextColor(120, 120, 120)
	pdf.MultiCell(pdfTextWidth, pdfLineHeightB,
		"This document was generated by LexScript. Output is deterministic: "+
			"identical inputs produce identical legal text (REQ-3.1). "+
			"No generative AI was used in the production of this document.",
		"", "C", false)
	pdf.SetTextColor(0, 0, 0)

	return pdf.OutputFileAndClose(outPath)
}

// ---------------------------------------------------------------------------
// PDF layout helpers
// ---------------------------------------------------------------------------

func hr(pdf *fpdf.Fpdf) {
	pdf.SetDrawColor(180, 180, 180)
	pdf.Line(pdfMarginLeft, pdf.GetY(), pdfMarginLeft+pdfTextWidth, pdf.GetY())
	pdf.SetDrawColor(0, 0, 0)
	pdf.Ln(4)
}

func pdfH1(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", pdfFontH1)
	pdf.Cell(0, pdfLineHeightH1, text)
	pdf.Ln(pdfLineHeightH1 + 2)
	pdf.SetFont("Helvetica", "", pdfFontBody)
}

func pdfH2(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", pdfFontH2)
	pdf.Cell(0, pdfLineHeightH2, text)
	pdf.Ln(pdfLineHeightH2 + 1)
	pdf.SetFont("Helvetica", "", pdfFontBody)
}

func pdfLabel(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", pdfFontBody)
	pdf.Cell(0, pdfLineHeightB, text)
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Ln(pdfLineHeightB)
}

// pdfWriteMixed renders a string that may contain **bold** segments.
// It splits on "**" and alternates between regular and bold font weight,
// using Write() so text flows and wraps naturally within the current margins.
// A line break is appended after all segments are written.
func pdfWriteMixed(pdf *fpdf.Fpdf, lineHeight float64, text string) {
	parts := strings.Split(text, "**")
	for i, part := range parts {
		if part == "" {
			continue
		}
		if i%2 == 1 {
			pdf.SetFont("Helvetica", "B", pdfFontBody)
		} else {
			pdf.SetFont("Helvetica", "", pdfFontBody)
		}
		pdf.Write(lineHeight, part)
	}
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Ln(lineHeight)
}

func pdfBody(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdfWriteMixed(pdf, pdfLineHeightB, text)
}

func pdfItalic(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "I", pdfFontBody)
	pdf.Write(pdfLineHeightB, text)
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Ln(pdfLineHeightB)
}

func pdfBullet(pdf *fpdf.Fpdf, text string) {
	// fpdf core fonts use WinAnsi (Windows-1252) encoding, not UTF-8.
	// U+2022 bullet lives at byte 0x95 in Windows-1252.
	const bullet = "\x95  "
	const indent = pdfMarginLeft + 6
	pdf.SetLeftMargin(indent)
	pdf.SetX(pdfMarginLeft + 4)
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Write(pdfLineHeightB, bullet)
	pdfWriteMixed(pdf, pdfLineHeightB, strings.TrimSpace(text))
	pdf.SetLeftMargin(pdfMarginLeft)
}

func signatureLine(pdf *fpdf.Fpdf, label string) {
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Cell(35, pdfLineHeightB, label+": ")
	pdf.SetFont("Helvetica", "", pdfFontBody)
	pdf.Cell(100, pdfLineHeightB, strings.Repeat("_", 45))
	pdf.Ln(pdfLineHeightB + 3)
}
